### ISSUE TITLE
First Screen, Text Change

### ISSUE THREAD

**Issue by sourcedexter** [vergecurrency/vDroid#12]
The first screen, to create a new wallet, says "iOS device". It needs to be changed to Android
![sketch-1549342972553](https://user-images.githubusercontent.com/5250647/52254056-7daae980-2931-11e9-8d65-d14a9160b361.jpg)

**Comment by 2lazy2debug** [comment]
Fixed here https://github.com/vergecurrency/vDroid/commit/b8583a8e91f1fd2f5d61b626a8f1d8507e2d02b2
