### ISSUE TITLE
New logo/icon proposal

### ISSUE THREAD

**Issue by mansya** [vergecurrency/vDroid#20]
Good day sir. I am a graphic designer and i am interested in designing a logo for your good project. I will be doing it as a gift for free. I just need your permission first before I begin my design. Hoping for your positive feedback. Thanks

**Comment by justinvforvendetta** [comment]
@mansya does it follow our branding? 

@waveon3

**Comment by waveon3** [comment]
@mansya feel free to share your designs :) No need for permission. Just make sure you follow our brand guidelines.
https://github.com/vergecurrency/verge-graphics/blob/master/brandguideline-verge.pdf

**Comment by 2lazy2debug** [comment]
Closing because that's not Wallet-only related.

**Comment by mansya** [comment]
did you reject this offer @2lazy2debug ?

**Comment by justinvforvendetta** [comment]
@mansya no one rejected the offer, this just isnt the place for it. please follow the link above that waveon3 posted, and make a pull request to that repository, thanks!

**Comment by 2lazy2debug** [comment]
@mansya Indeed I just pointed out that this isn't the right place for such an offer, but I'm glad you made it! follow the link that  @waveon3 gave you and you're more than welcome to contribute and we're always happy to see people involved in our project! Thank you for you contribution :)
