### ISSUE TITLE
Redesign the filter bar in transaction views

### ISSUE THREAD

**Issue by 2lazy2debug** [vergecurrency/vDroid#34]
Related to #33 , the filter look is pretty amateur-ish (my fault) , needs a new look.

**Comment by ghost** [comment]
![filter example](https://user-images.githubusercontent.com/58558820/73395790-7b7b3100-42e0-11ea-85f4-8bcc13593caf.JPG)

**Comment by ghost** [comment]
![filter example 2](https://user-images.githubusercontent.com/58558820/73593369-d476df00-4503-11ea-8429-59b2baf8ecbc.JPG)

**Comment by ghost** [comment]
![filter example moon mode](https://user-images.githubusercontent.com/58558820/73598569-58e45480-453a-11ea-8060-2adde7b58d1f.JPG)

**Comment by ghost** [comment]
![tx detail example](https://user-images.githubusercontent.com/58558820/73598604-c0020900-453a-11ea-93cc-a3a5ada469d0.JPG)
