### ISSUE TITLE
QR code isn't scanable

### ISSUE THREAD

**Issue by SwenVanZanten** [vergecurrency/vDroid#53]
Hello dear Android developers,

I've noticed in the current version the QR code generated on the receive view isn't scan-able.
It seems like a part of the code is chopped off 💯 

Here's an example:
https://twitter.com/justinvendetta/status/1234303469286313984/photo/1

**Comment by justinvforvendetta** [comment]
Rome wasn't built in a day ;p

**Comment by 2lazy2debug** [comment]
Fixed here https://github.com/vergecurrency/vDroid/commit/ddda93ed6b61b50cf7a0813e243ab6c61739eaa3

**Comment by justinvforvendetta** [comment]
sex.
