### ISSUE TITLE
For more security spongycastle -> bouncycastle

### ISSUE THREAD

**Issue by Neustradamus** [vergecurrency/vDroid#54]
For more security, can you change old spongycastle (based on old bouncycastle) to bouncycastle?
- https://www.bouncycastle.org/
- https://www.bouncycastle.org/releasenotes.html
- http://www.bouncycastle.org/latest_releases.html
- https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=bouncy%20castle
- https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=bouncycastle
- https://www.cvedetails.com/vulnerability-list/vendor_id-7637/Bouncycastle.html

**Comment by Neustradamus** [comment]
@PuuTheBear, @2lazy2debug: Always here:
- https://github.com/vergecurrency/vDroid/search?q=spongycastle&unscoped_q=spongycastle

**Comment by Neustradamus** [comment]
@PuuTheBear, @2lazy2debug: Any news?

**Comment by justinvforvendetta** [comment]
im sure it can be changed. you know this app isnt live yet right?

**Comment by 2lazy2debug** [comment]
@Neustradamus @justinvforvendetta it has been fixed a couple of commits ago, closing.

**Comment by Neustradamus** [comment]
@2lazy2debug, @justinvforvendetta: Always here: https://github.com/vergecurrency/vDroid/search?q=spongycastle&unscoped_q=spongycastle

**Comment by 2lazy2debug** [comment]
one is an old output file, the other a comment i didn’t remove. please, before questioning us check what are you saying.

thanks and good night.

**Comment by Neustradamus** [comment]
If it is done, there is no need to have "//TODO UPDATE SPONGYCASTLE -> BOUNCYCASTLE"

**Comment by Neustradamus** [comment]
@2lazy2debug: Can you remove the old parts?
- https://github.com/vergecurrency/vDroid/search?q=spongycastle&unscoped_q=spongycastle
