### ISSUE TITLE
Create currencies view

### ISSUE THREAD

**Issue by 2lazy2debug** [vergecurrency/vDroid#9]
- [x] Create listview with custom arrayadapter + onclicklistener

- [x] On Click, change default currency and close the activity

- [x] Style the activity correctly

- [ ] Show the already default currency

**Comment by ghost** [comment]
![currencies view feather](https://user-images.githubusercontent.com/58558820/73611792-c4cfc700-45e5-11ea-9483-8722751f6839.JPG)
![currencies view](https://user-images.githubusercontent.com/58558820/73611793-c5685d80-45e5-11ea-896c-0a5a42d01808.JPG)
